import { createRequire } from 'node:module';
import path from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';

const require = createRequire(import.meta.url);

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      react: path.dirname(require.resolve('react/package.json')),
      'react-dom': path.dirname(require.resolve('react-dom/package.json')),
    },
    dedupe: ['react', 'react-dom'],
  },
  build: {
    lib: {
      entry: path.resolve(import.meta.dirname, 'src/index.js'),
      formats: ['es'],
      fileName: 'index',
    },
    rollupOptions: {
      external: [
        'react',
        'react-dom',
        'react-dom/client',
        'react/jsx-runtime',
        'react-router-dom',
        '@mantine/core',
        '@mantine/charts',
        '@mantine/dates',
        '@mantine/dropzone',
        '@mantine/form',
        '@mantine/hooks',
        '@mantine/modals',
        '@mantine/tiptap',
        '@mui/material',
        '@mui/x-data-grid',
        '@emotion/react',
        '@emotion/styled',
        '@tiptap/core',
        '@tiptap/react',
        '@tiptap/starter-kit',
        '@tiptap/extension-color',
        '@tiptap/extension-details',
        '@tiptap/extension-details-content',
        '@tiptap/extension-details-summary',
        '@tiptap/extension-highlight',
        '@tiptap/extension-image',
        '@tiptap/extension-link',
        '@tiptap/extension-placeholder',
        '@tiptap/extension-subscript',
        '@tiptap/extension-superscript',
        '@tiptap/extension-table',
        '@tiptap/extension-table-cell',
        '@tiptap/extension-table-header',
        '@tiptap/extension-table-row',
        '@tiptap/extension-text-align',
        '@tiptap/extension-text-style',
        '@tiptap/extension-underline',
        '@tiptap/extension-youtube',
        '@tiptap/pm',
        'tiptap-extension-font-size',
        '@hello-pangea/dnd',
        '@fortawesome/fontawesome-svg-core',
        '@fortawesome/free-brands-svg-icons',
        '@fortawesome/free-solid-svg-icons',
        '@fortawesome/react-fontawesome',
        '@capacitor/app',
        '@capacitor/core',
        '@capacitor/device',
        '@capacitor/preferences',
        'i18next',
        'i18next-browser-languagedetector',
        'i18next-http-backend',
        'react-i18next',
        'zustand',
        'dayjs',
        'lodash',
        'recharts',
        'react-helmet',
        'react-device-detect',
        'react-simple-code-editor',
        'prismjs',
      ],
    },
    outDir: 'dist',
    sourcemap: true,
    cssCodeSplit: false,
  },
});
